In [1]:
height = float(input('Height in meters: '))
weight = int(input('Weight in kg: '))
bmi = weight/(height*height)
print (bmi)

Height in meters: 1.85
Weight in kg: 85
24.835646457268076


In [2]:
quarters = int(input("Quarters: "))
dimes = int(input("Dimes: "))
nickels = int(input("Nickels: "))
pennies = int(input("Pennies: "))
total = quarters * .25 + dimes * .10 + nickels * .05 + pennies * .01
print ("The total value of your change is", total)

Quarters: 4
Dimes: 10
Nickels: 20
Pennies: 100
The total value of your change is 4.0


In [10]:
days = int(input("Number of days: ")) * 3600 * 24
hours = int(input("Number ofhours: ")) * 3600
minutes = int(input("Number of minutes: ")) * 60
seconds = int(input("Number of seconds: "))

time = days + hours + minutes + seconds

print("Total number of seconds", time)

Number of days: 2
Number ofhours: 2
Number of minutes: 2
Number of seconds: 2
Total number of seconds 180122


In [9]:
list1=[26,1,43,21,33,106,45,4,10,3,51,56,65]
import numpy as np
print('Sorted Array : ',np.sort(list1))
print('Mean : ',np.mean(list1))
print('Median : ',np.median(list1))

Sorted Array :  [  1   3   4  10  21  26  33  43  45  51  56  65 106]
Mean :  35.69230769230769
Median :  33.0


In [19]:
import math
print('PI',math.pi)
radius = 2
print('The area of a circle with a radius of 2 is:', math.pi * (radius ** 2))
print("Euler's number:",math.e)
print((math.e + 6 / 2) * 4.32)

print('Exp E:',math.exp(math.e))
print('Exp PI:',math.exp(math.pi))

PI 3.141592653589793
The area of a circle with a radius of 2 is: 12.566370614359172
Euler's number: 2.718281828459045
24.702977498943074
Exp E: 15.154262241479262
Exp PI: 23.140692632779267


In [17]:
import math

# Initializing values
an_int = 6
a_neg_int = -8
a_float = 2.00

# Pass the values to exp() method and print
print(math.exp(an_int))
print(math.exp(a_neg_int))
print(math.exp(a_float))

403.4287934927351
0.00033546262790251185
7.38905609893065


In [22]:
import math

print("math.log(10.43):", math.log(10.43))
print("math.log(20):", math.log(20))
print("math.log(math.pi):", math.log(math.pi))

# Returns the log10 of 50
print("The log10 of 50 is:", math.log10(50))

# Returns the log2 of 16
print("The log2 of 16 is:", math.log2(16))

# Returns the log of 3,4
print("The log 3 with base 4 is:", math.log(3, 4))

print("Logarithm(1+x) value of 10 is:", math.log1p(10))

math.log(10.43): 2.344686269012681
math.log(20): 2.995732273553991
math.log(math.pi): 1.1447298858494002
The log10 of 50 is: 1.6989700043360187
The log2 of 16 is: 4.0
The log 3 with base 4 is: 0.7924812503605781
Logarithm(1+x) value of 10 is: 2.3978952727983707


In [23]:
import math

num = -4.28
a = 14
b = 8
num_list = [10, 8.25, 75, 7.04, -86.23, -6.43, 8.4]
x = 1e-4 # A small value of x

print('The number is:', num)
print('The floor value is:', math.floor(num))
print('The ceiling value is:', math.ceil(num))
print('The absolute value is:', math.fabs(num))
print('The GCD of a and b is: ' + str(math.gcd(a, b)))
print('Sum of the list elements is: ' + str(math.fsum(num_list)))
print('e^x (using function exp()) is:', math.exp(x)-1)
print('e^x (using function expml()) is:', math.expm1(x))

The number is: -4.28
The floor value is: -5
The ceiling value is: -4
The absolute value is: 4.28
The GCD of a and b is: 2
Sum of the list elements is: 16.029999999999998
e^x (using function exp()) is: 0.0001000050001667141
e^x (using function expml()) is: 0.00010000500016667084


In [24]:
import math

angle_In_Degrees = 62
angle_In_Radians = math.radians(angle_In_Degrees)

print('The value of the angle is:', angle_In_Radians)
print('sin(x) is:', math.sin(angle_In_Radians))
print('tan(x) is:', math.tan(angle_In_Radians))
print('cos(x) is:', math.cos(angle_In_Radians))

The value of the angle is: 1.0821041362364843
sin(x) is: 0.8829475928589269
tan(x) is: 1.8807264653463318
cos(x) is: 0.46947156278589086


In [26]:
def quicksort(arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return quicksort(left) + middle + quicksort(right)

print(quicksort([3,6,8,10,1,2,1]))

[1, 1, 2, 3, 6, 8, 10]


In [27]:
import numpy as np
a  = np.array([1,2,3])
print(a.shape)
print(a.dtype)

#### Different type
b  = np.array([1.1,2.0,3.2])
print(b.dtype)

### 2 dimension
c = np.array([(1,2,3),
              (4,5,6)])
print(c.shape)

### 3 dimension
d = np.array([
    [[1, 2,3],
        [4, 5, 6]],
    [[7, 8,9],
        [10, 11, 12]]
])
print(d.shape)

(3,)
int32
float64
(2, 3)
(2, 2, 3)


In [28]:
import numpy as np
print('numpy zero:',np.zeros((2,2)))

print('numpy zero datatype:',np.zeros((2,2), dtype=np.int16))

print('numpy one 2D Array with datatype:',np.ones((1,2,3), dtype=np.int16))

numpy zero: [[0. 0.]
 [0. 0.]]
numpy zero datatype: [[0 0]
 [0 0]]
numpy one 2D Array with datatype: [[[1 1 1]
  [1 1 1]]]


In [30]:
import numpy as np
e  = np.array([(1,2,3), (4,5,6)])
print(e)
e.reshape(3,2)

e.flatten()

[[1 2 3]
 [4 5 6]]


array([1, 2, 3, 4, 5, 6])

In [32]:
## Horitzontal Stack
import numpy as np
f = np.array([1,2,3])
g = np.array([4,5,6])

print('Horizontal Append:', np.hstack((f, g)))

## Vertical Stack
import numpy as np
f = np.array([1,2,3])
g = np.array([4,5,6])

print('Vertical Append:', np.vstack((f, g)))

## Generate random nmber from normal distribution
normal_array = np.random.normal(5, 0.5, 10)
print(normal_array)	

Horizontal Append: [1 2 3 4 5 6]
Vertical Append: [[1 2 3]
 [4 5 6]]
[4.68489632 5.33777004 5.01956691 4.09819423 5.16268406 4.45930823
 6.12045644 5.30620246 4.33356879 5.37419298]


In [35]:
import numpy as np
A = np.matrix(np.ones((4,4)))
print(A)

np.asarray(A)[2]=2
print(A)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [1. 1. 1. 1.]]


In [39]:
import numpy as np
a = np.arange(1, 11)
print(a)
b = np.arange(1, 14, 4)
print(b)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  5  9 13]


In [42]:
import numpy as np

#create 10 values from 1 to 5 evenly spaced
a = np.linspace(1.0, 5.0, num=10)

print(a)

#not want to include the last digit in the interval
b = np.linspace(1.0, 5.0, num=5, endpoint=False)

print(b)

#returns even spaced numbers on a log scale
c = np.logspace(3.0, 4.0, num=4)

print(c)

#check the size of an array
x = np.array([1,2,3], dtype=np.complex128)
x.itemsize

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]
[1.  1.8 2.6 3.4 4.2]
[ 1000.          2154.43469003  4641.58883361 10000.        ]


16

In [48]:
## Slice
import numpy as np
e  = np.array([(1,2,3), (4,5,6)])
print(e)

## First row
print('First row:', e[0])

## Second row
print('Second row:', e[1])

print('Second column:', e[:,1])

## Second Row, two values
print(e[1, :2])

[[1 2 3]
 [4 5 6]]
First row: [1 2 3]
Second row: [4 5 6]
Second column: [2 5]
[4 5]


In [49]:
import numpy as np
normal_array = np.random.normal(5, 0.5, 10)
print(normal_array)

### Min 
print(np.min(normal_array))

### Max 
print(np.max(normal_array))

### Mean 
print(np.mean(normal_array))

### Median
print(np.median(normal_array))

### Sd
print(np.std(normal_array))

[4.28652589 5.55193378 4.0653692  4.68320737 4.84754857 4.71037272
 5.08352383 4.52881676 5.67051969 5.82584014]
4.065369195266315
5.825840138068
4.925365793054442
4.778960641128759
0.5656491608870244


In [50]:
## Linear algebra
### Dot product: product of two arrays
f = np.array([1,2])
g = np.array([4,5])
### 1*4+2*5
np.dot(f, g)

14

In [52]:
### Matmul: matruc product of two arrays
h = [[1,2],[3,4]] 
i = [[5,6],[7,8]] 
### 1*5+2*7 = 19
print('Matmul:',np.matmul(h, i))

## Determinant 2*2 matrix
### 5*8-7*6
print('Determinate:',np.linalg.det(i))

Matmul: [[19 22]
 [43 50]]
Determinate: -1.999999999999999
