In [1]:
def greet_john_function():
    print("Hello John")
    print("How are you?")
greet_john_function()

Hello John
How are you?


In [2]:
def greet_function(person):
    print("Hello" + person)
    print("How are you?")
greet_function(' John')

Hello John
How are you?


In [3]:
def multiply(a,b,c):
    return a*b*c
multiply(2,4,5)

40

In [4]:
multiply_a=multiply(2,4,5)
print (multiply_a)

40


In [5]:
def function_a():
    global b
    a=2
    b=3
    return a + b
def function_b():
    c=5
    return b+c
function_a()
function_b()

8

In [6]:
def function_sum(a,b,c,d,e,f):
    return a+b+c+d+e+f;
function_sum(5,8,2,4,7,9)

35

In [7]:
def function_multipy(a,b,c,d,e):
    return a*b*c*d*e;
function_multipy(4,3,5,6,2)

720

In [8]:
##Creating an empty list
empty_list=[]

## Creating a list of numbers
number_list=[1,5,3,7,9]

## Creating a list of strings
string_list=['s', 'r', 'q']

In [9]:
number_list

[1, 5, 3, 7, 9]

In [10]:
string_list

['s', 'r', 'q']

In [11]:
list_of_lists=[string_list,number_list]

In [12]:
list_of_lists

[['s', 'r', 'q'], [1, 5, 3, 7, 9]]

In [13]:
combined_list=string_list + number_list
combined_list

['s', 'r', 'q', 1, 5, 3, 7, 9]

In [14]:
combined_list[:4]

['s', 'r', 'q', 1]

In [15]:
combined_list[4:8]

[5, 3, 7, 9]

In [16]:
tuple1=(6,5,8,9,10,12)

In [17]:
tuple1

(6, 5, 8, 9, 10, 12)

In [18]:
## Casting from Tuple to List

tuple1_list=list(tuple1)

In [19]:
tuple1_list

[6, 5, 8, 9, 10, 12]

In [20]:
list1=['a','b','c','d','e','f','g']

In [21]:
list1

['a', 'b', 'c', 'd', 'e', 'f', 'g']

In [22]:
tuple_list1=tuple(list1)

In [23]:
tuple_list1

('a', 'b', 'c', 'd', 'e', 'f', 'g')

In [24]:
Gender_code_dictionary={"female":1, "male":2, "unknown":3}

In [25]:
Gender_code_dictionary

{'female': 1, 'male': 2, 'unknown': 3}

In [26]:
Gender_code_dictionary["male"]

2

In [27]:
Gender_code_dictionary["female"]

1

In [28]:
import numpy as np

a=np.array([[4,5,6],[3,2,5]])
type(a)

numpy.ndarray

In [29]:
a.ndim ## Lists the dimensions of the array 2

2

In [30]:
a.shape ## Lists the shape of the array 2 rows X 3 columns

(2, 3)

In [31]:
a.size ## Lists the size or numbe of elements in an array

6

In [81]:
a.dtype ## Lists the data types of the array's elements.

dtype('int32')

In [33]:
a.itemsize ## Lists the size of a single item in the array in bytes

4

In [34]:
a.nbytes ## Total size of memory consumed by all the elements in an array in bytes. In this case it is 6X4 bytes

24

In [35]:
## Creating arrays from a list with float16 data type
array1=np.array([[3,5,6,8,9],[6,7,5,4,5],[9,7,6,4,3]], dtype='float16')
print(array1)

[[3. 5. 6. 8. 9.]
 [6. 7. 5. 4. 5.]
 [9. 7. 6. 4. 3.]]


In [36]:
## Creating arrays from tuples
array2=np.array(((4,3,5,7),(7,8,8,9)))
print (array2)

[[4 3 5 7]
 [7 8 8 9]]


In [37]:
## Creating an array populated with random values:
np.random.random((4,5))

array([[0.89273964, 0.96129704, 0.1243408 , 0.59783199, 0.70420899],
       [0.57249756, 0.70675661, 0.93845825, 0.45123091, 0.06013336],
       [0.51869951, 0.14392051, 0.62968925, 0.29891973, 0.45579574],
       [0.79231756, 0.62220706, 0.75247483, 0.83280938, 0.2736712 ]])

In [38]:
## Creating a 5X8  array populated with zeros
array3=np.zeros((5,8))
print(array3)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [39]:
## Creating a sequence of integers from 14 49 with steps of 7
array4=np.arange(14,49,7)
print(array4)

[14 21 28 35 42]


In [40]:
## Craeting an array of 20 sequential values between 10 and 15 
array4 = np.linspace(10, 15, 20)
print(array4)

[10.         10.26315789 10.52631579 10.78947368 11.05263158 11.31578947
 11.57894737 11.84210526 12.10526316 12.36842105 12.63157895 12.89473684
 13.15789474 13.42105263 13.68421053 13.94736842 14.21052632 14.47368421
 14.73684211 15.        ]


In [41]:
## Flattening an Array
print('array1:')
print(array1)
print('')
print('flattened array1:')
flat_array1=array1.flatten()
print (flat_array1)

array1:
[[3. 5. 6. 8. 9.]
 [6. 7. 5. 4. 5.]
 [9. 7. 6. 4. 3.]]

flattened array1:
[3. 5. 6. 8. 9. 6. 7. 5. 4. 5. 9. 7. 6. 4. 3.]


In [42]:
## Reshaping a 4X6 array to a 2X2X6
array5=np.random.random((4,6))
print (array5)
print('')
print('Reshaped array:')
reshaped_array5=array5.reshape(2,2,6)
print(reshaped_array5)

[[0.45936598 0.91907118 0.63192014 0.8292706  0.91521126 0.70234858]
 [0.34836339 0.62771229 0.75707281 0.71742966 0.73798311 0.8488235 ]
 [0.23953956 0.09332094 0.1856224  0.22623004 0.96046816 0.11974147]
 [0.93094115 0.65910806 0.78755929 0.46076193 0.95707432 0.77218989]]

Reshaped array:
[[[0.45936598 0.91907118 0.63192014 0.8292706  0.91521126 0.70234858]
  [0.34836339 0.62771229 0.75707281 0.71742966 0.73798311 0.8488235 ]]

 [[0.23953956 0.09332094 0.1856224  0.22623004 0.96046816 0.11974147]
  [0.93094115 0.65910806 0.78755929 0.46076193 0.95707432 0.77218989]]]


In [43]:
print (array1)

[[3. 5. 6. 8. 9.]
 [6. 7. 5. 4. 5.]
 [9. 7. 6. 4. 3.]]


In [44]:
## Adding 2 to each element in array1
print (array1 + 2)

[[ 5.  7.  8. 10. 11.]
 [ 8.  9.  7.  6.  7.]
 [11.  9.  8.  6.  5.]]


In [45]:
## Subtracting 2 to each element in array1
print (array1 - 2)

[[1. 3. 4. 6. 7.]
 [4. 5. 3. 2. 3.]
 [7. 5. 4. 2. 1.]]


In [46]:
## Multiplying each element in array by 2
print (array1 * 2)

[[ 6. 10. 12. 16. 18.]
 [12. 14. 10.  8. 10.]
 [18. 14. 12.  8.  6.]]


In [47]:
## Dividing each element in array by 2
print (array1/2)

[[1.5 2.5 3.  4.  4.5]
 [3.  3.5 2.5 2.  2.5]
 [4.5 3.5 3.  2.  1.5]]


In [48]:
## Squaring each element in array:
print (array1**2)

[[ 9. 25. 36. 64. 81.]
 [36. 49. 25. 16. 25.]
 [81. 49. 36. 16.  9.]]


In [49]:
## Transposing an array
print('Original Array:')
print (array1)
print('')
print('Array1 Transposed')
print(array1.T)

Original Array:
[[3. 5. 6. 8. 9.]
 [6. 7. 5. 4. 5.]
 [9. 7. 6. 4. 3.]]

Array1 Transposed
[[3. 6. 9.]
 [5. 7. 7.]
 [6. 5. 6.]
 [8. 4. 4.]
 [9. 5. 3.]]


In [50]:
## The maximum function lists the largest element of the array as follows:
array1.max()

9.0

In [51]:
## Applying max function row-wise
array1.max(axis=1)

array([9., 7., 9.], dtype=float16)

In [52]:
## Applying max function column-wise
array1.max(axis=0)

array([9., 7., 6., 8., 9.], dtype=float16)

In [53]:
## The minimum function lists the largest element of the array as follows:
array1.min()

3.0

In [54]:
## Applying min function row-wise
array1.min(axis=1)

array([3., 4., 3.], dtype=float16)

In [55]:
## Applying min function column-wise
array1.min(axis=0)

array([3., 5., 5., 4., 3.], dtype=float16)

In [56]:
## Computing sum of all array elements
array1.sum()

87.0

In [57]:
## Computing sum of all array elements row-wise
array1.sum(axis=1)

array([31., 27., 29.], dtype=float16)

In [58]:
## Computing sum of all array elements column-wise
array1.sum(axis=0)

array([18., 19., 17., 16., 17.], dtype=float16)

In [59]:
np.sqrt(array1)

array([[1.732, 2.236, 2.45 , 2.828, 3.   ],
       [2.45 , 2.646, 2.236, 2.   , 2.236],
       [3.   , 2.646, 2.45 , 2.   , 1.732]], dtype=float16)

In [60]:
np.sin(array1)

array([[ 0.1411, -0.959 , -0.2793,  0.9893,  0.412 ],
       [-0.2793,  0.657 , -0.959 , -0.757 , -0.959 ],
       [ 0.412 ,  0.657 , -0.2793, -0.757 ,  0.1411]], dtype=float16)

In [61]:
np.cos(array1)

array([[-0.99  ,  0.2837,  0.96  , -0.1455, -0.911 ],
       [ 0.96  ,  0.754 ,  0.2837, -0.654 ,  0.2837],
       [-0.911 ,  0.754 ,  0.96  , -0.654 , -0.99  ]], dtype=float16)

In [62]:
## Sorting regardless of dimensions and structure/flattened list of array elements
print ('Array1:')
print (array1)
print('')
print('Array1 Simple Sort:')
np.sort(array1, axis=None)

Array1:
[[3. 5. 6. 8. 9.]
 [6. 7. 5. 4. 5.]
 [9. 7. 6. 4. 3.]]

Array1 Simple Sort:


array([3., 3., 4., 4., 5., 5., 5., 6., 6., 6., 7., 7., 8., 9., 9.],
      dtype=float16)

In [63]:
## Sorting along the row of arrays, Python will sort by row by default if no axis is specified:
print ('Array1:')
print (array1)
print('')
print('Array1 Simple Sort:')
np.sort(array1)

Array1:
[[3. 5. 6. 8. 9.]
 [6. 7. 5. 4. 5.]
 [9. 7. 6. 4. 3.]]

Array1 Simple Sort:


array([[3., 5., 6., 8., 9.],
       [4., 5., 5., 6., 7.],
       [3., 4., 6., 7., 9.]], dtype=float16)

In [64]:
## The same result can also be obtained by specifying the row axis as follows:
print ('Array1:')
print (array1)
print('')
print('Array1 Simple Sort:')
np.sort(array1, axis=1)

Array1:
[[3. 5. 6. 8. 9.]
 [6. 7. 5. 4. 5.]
 [9. 7. 6. 4. 3.]]

Array1 Simple Sort:


array([[3., 5., 6., 8., 9.],
       [4., 5., 5., 6., 7.],
       [3., 4., 6., 7., 9.]], dtype=float16)

In [65]:
## Sorting an array by column/column-wise:
print ('Array1:')
print (array1)
print('')
print('Array1 Simple Sort:')
np.sort(array1, axis=0)

Array1:
[[3. 5. 6. 8. 9.]
 [6. 7. 5. 4. 5.]
 [9. 7. 6. 4. 3.]]

Array1 Simple Sort:


array([[3., 5., 5., 4., 3.],
       [6., 7., 6., 4., 5.],
       [9., 7., 6., 8., 9.]], dtype=float16)

In [66]:
##Slicing elements from 3rd row
print(array1[2,...])

[9. 7. 6. 4. 3.]


In [67]:
print (array1)

[[3. 5. 6. 8. 9.]
 [6. 7. 5. 4. 5.]
 [9. 7. 6. 4. 3.]]


In [68]:
##Slicing elements from 0 row
print(array1[0,...])

[3. 5. 6. 8. 9.]


In [69]:
##Slicing elements from second row
print(array1[1,...])

[6. 7. 5. 4. 5.]


In [70]:
## obtaining the elements from the second row onward is done as follows:
print(array1[1:,...])

[[6. 7. 5. 4. 5.]
 [9. 7. 6. 4. 3.]]


In [71]:
## obtaining the elements from of first 2 rows:
print(array1[:2,...])

[[3. 5. 6. 8. 9.]
 [6. 7. 5. 4. 5.]]


In [72]:
## Slicing elements of 3rd column example:
print(array1[...,2])

[6. 5. 6.]


In [73]:
## Slicing elements of first column example:
print(array1[...,0])

[3. 6. 9.]


In [74]:
## Slicing elements of second column example:
print(array1[...,1])

[5. 7. 7.]


In [75]:
## obtaining the elements from the second column onwards is done as follows:
print(array1[...,1:])

[[5. 6. 8. 9.]
 [7. 5. 4. 5.]
 [7. 6. 4. 3.]]


In [76]:
##obtaining elements of first three columns:
print(array1[...,:3])

[[3. 5. 6.]
 [6. 7. 5.]
 [9. 7. 6.]]


In [77]:
##Slice element from first row and second column:
print ('Array1:')
print (array1)
print('')
print('Element sliced from first row and second column:')
print(array1[0,1])

Array1:
[[3. 5. 6. 8. 9.]
 [6. 7. 5. 4. 5.]
 [9. 7. 6. 4. 3.]]

Element sliced from first row and second column:
5.0


In [78]:
##Slice element from third row and fourth column:
print ('Array1:')
print (array1)
print('')
print('Element sliced from third row and fourth column:')
print(array1[2,3])

Array1:
[[3. 5. 6. 8. 9.]
 [6. 7. 5. 4. 5.]
 [9. 7. 6. 4. 3.]]

Element sliced from third row and fourth column:
4.0


In [79]:
array_hw=np.array([[5,5,8,8,9,8],[7,7,5,3,5,7],[8,7,8,4,2,6],[9,9,7,3,1,4]])
print(array_hw)

[[5 5 8 8 9 8]
 [7 7 5 3 5 7]
 [8 7 8 4 2 6]
 [9 9 7 3 1 4]]


In [80]:
## Sorting regardless of dimensions and structure/flattened list of array elements
print ('array_hw:')
print (array_hw)
print('')
print('array_hw Simple Sort:')
np.sort(array_hw, axis=None)

array_hw:
[[5 5 8 8 9 8]
 [7 7 5 3 5 7]
 [8 7 8 4 2 6]
 [9 9 7 3 1 4]]

array_hw Simple Sort:


array([1, 2, 3, 3, 4, 4, 5, 5, 5, 5, 6, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 9,
       9, 9])

In [105]:
array_hw=np.array([[5,5,8,8,9,8],[7,7,5,3,5,7],[8,7,8,4,2,6],[9,9,7,3,1,4]])
array_hw[array_hw[:,1].argsort()]

array([[5, 5, 8, 8, 9, 8],
       [7, 7, 5, 3, 5, 7],
       [8, 7, 8, 4, 2, 6],
       [9, 9, 7, 3, 1, 4]])

In [111]:
array_hw[:, array_hw[2].argsort()]
#print(array_hw)

array([[9, 8, 8, 5, 5, 8],
       [5, 3, 7, 7, 7, 5],
       [2, 4, 6, 7, 8, 8],
       [1, 3, 4, 9, 9, 7]])

In [112]:
array_hw[1,:]

array([7, 7, 5, 3, 5, 7])

In [113]:
array_hw[:,2]

array([8, 5, 8, 7])

In [115]:
np.sqrt(array_hw)

array([[2.23606798, 2.23606798, 2.82842712, 2.82842712, 3.        ,
        2.82842712],
       [2.64575131, 2.64575131, 2.23606798, 1.73205081, 2.23606798,
        2.64575131],
       [2.82842712, 2.64575131, 2.82842712, 2.        , 1.41421356,
        2.44948974],
       [3.        , 3.        , 2.64575131, 1.73205081, 1.        ,
        2.        ]])

In [118]:
print(array_hw[2,...,3])

4


In [119]:
array_hw.sum()

145

In [120]:
array_hw.ndim

2

In [121]:
array_hw.dtype

dtype('int32')

In [122]:
array_hw.nbytes 

96